import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import {
  buildTaskPrompt,
  chooseCopilotModel,
  runCopilotPrompt
} from "../providers/coder/copilot_cli_provider.js";
import { writeFallbackPatchNote } from "../providers/coder/fallback_provider.js";

const taskId = process.argv[2] ?? "0";
const taskTitle = process.argv[3] ?? "Unnamed task";
const taskKind = process.argv[4] ?? "general";
const repo = process.env.TARGET_REPO;
const baseBranch = process.env.TARGET_BASE_BRANCH || "main";
const token = process.env.GITHUB_TOKEN;
const copilotCommand = process.env.COPILOT_CLI_COMMAND || "copilot";
const copilotStrategy = process.env.COPILOT_STRATEGY || "task-best";
const copilotAllowedModels = process.env.COPILOT_ALLOWED_MODELS || "";
const copilotNeverUseModels = process.env.COPILOT_NEVER_USE_MODELS || "";
const copilotMaxMultiplier = process.env.COPILOT_MAX_MULTIPLIER || "1";
const copilotModelMultipliers = process.env.COPILOT_MODEL_MULTIPLIERS_JSON || "{}";
const copilotDefaultModel = process.env.COPILOT_DEFAULT_MODEL || "Claude Sonnet 4.5";
const copilotOpusModel = process.env.COPILOT_OPUS_MODEL || "Claude Opus 4.6";
const copilotAllowOpusEscalation = ["1", "true", "yes", "on"].includes(String(process.env.COPILOT_ALLOW_OPUS_ESCALATION || "false").toLowerCase());
const copilotTeamLeadAllowOpus = ["1", "true", "yes", "on"].includes(String(process.env.COPILOT_TEAM_LEAD_ALLOW_OPUS || "false").toLowerCase());
const copilotTeamLeadReason = process.env.COPILOT_TEAM_LEAD_REASON || "";
const copilotOpusEscalationKeywords = process.env.COPILOT_OPUS_ESCALATION_KEYWORDS || "";
const copilotPreferredByTaskKind = process.env.COPILOT_PREFERRED_MODELS_BY_TASK_KIND_JSON || "{}";
const boxSelectedAgent = process.env.BOX_SELECTED_AGENT || "box-coder";
const boxPromptFile = process.env.BOX_PROMPT_FILE || "";
const boxPromptTemplateText = process.env.BOX_PROMPT_TEMPLATE_TEXT || "";
const boxAutoCreatePr = ["1", "true", "yes", "on"].includes(String(process.env.BOX_AUTO_CREATE_PR || "true").toLowerCase());

function parseRepoTarget(repoTarget) {
  const [owner, name] = String(repoTarget || "").split("/");
  if (!owner || !name) {
    return null;
  }
  return { owner, name };
}

async function createPullRequest({ repoTarget, tokenValue, branchName, baseRef, title, taskKindValue, taskIdValue }) {
  const parsedRepo = parseRepoTarget(repoTarget);
  if (!parsedRepo) {
    return { ok: false, reason: "invalid target repo format" };
  }

  const payload = {
    title: `BOX: ${title}`,
    head: branchName,
    base: baseRef,
    body: [
      `Automated BOX task completion for #${taskIdValue}.`,
      `Task kind: ${taskKindValue}.`,
      "",
      "Generated by BOX worker runtime."
    ].join("\n")
  };

  const response = await fetch(`https://api.github.com/repos/${parsedRepo.owner}/${parsedRepo.name}/pulls`, {
    method: "POST",
    headers: {
      "Accept": "application/vnd.github+json",
      "Authorization": `Bearer ${tokenValue}`,
      "User-Agent": "box-orchestrator"
    },
    body: JSON.stringify(payload)
  });

  const responseText = await response.text();
  const hasAlreadyExistsMessage = response.status === 422 && responseText.toLowerCase().includes("already exists");
  if (response.ok || hasAlreadyExistsMessage) {
    return { ok: true, reason: response.ok ? "created" : "already-exists" };
  }

  return { ok: false, reason: `github api status ${response.status}` };
}

function run(command) {
  execSync(command, { stdio: "inherit" });
}

function hasCommand(command) {
  try {
    execSync(`${command} --version`, { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function detectNodeProject() {
  return fs.existsSync(path.join(process.cwd(), "package.json"));
}

function safeTry(command) {
  try {
    run(command);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  if (!repo || !token) {
    console.error("missing TARGET_REPO or GITHUB_TOKEN");
    process.exit(2);
  }

  const branch = `box/task-${taskId}`;
  run(`git clone https://x-access-token:${token}@github.com/${repo}.git repo`);
  process.chdir("repo");
  run(`git checkout ${baseBranch}`);
  run(`git checkout -b ${branch}`);

  const fallbackPrompt = buildTaskPrompt({ taskTitle, taskKind });
  const prompt = String(boxPromptTemplateText || "").trim() || fallbackPrompt;

  const modelDecision = chooseCopilotModel({
    strategy: copilotStrategy,
    taskTitle,
    taskKind,
    defaultModel: copilotDefaultModel,
    preferredModelsByTaskKindJson: copilotPreferredByTaskKind,
    opusModel: copilotOpusModel,
    allowOpusEscalation: copilotAllowOpusEscalation,
    teamLeadAllowOpus: copilotTeamLeadAllowOpus,
    teamLeadReason: copilotTeamLeadReason,
    opusEscalationKeywordsCsv: copilotOpusEscalationKeywords,
    neverUseModelsCsv: copilotNeverUseModels,
    allowedModelsCsv: copilotAllowedModels,
    maxMultiplier: copilotMaxMultiplier,
    multipliersJson: copilotModelMultipliers
  });

  if (hasCommand(copilotCommand)) {
    const used = runCopilotPrompt(copilotCommand, prompt, modelDecision);
    console.log(`BOX_COPILOT_META=${JSON.stringify({ taskId, taskKind, requestedStrategy: copilotStrategy, selectedAgent: boxSelectedAgent, promptFile: boxPromptFile, ...used })}`);
  } else {
    await writeFallbackPatchNote(taskId, taskTitle);
    console.log(`BOX_COPILOT_META=${JSON.stringify({ taskId, taskKind, selectedAgent: boxSelectedAgent, promptFile: boxPromptFile, invocation: "fallback-provider" })}`);
  }

  if (detectNodeProject()) {
    safeTry("npm ci");
    if (!safeTry("npm run build")) {
      console.error("build failed");
      process.exit(3);
    }

    if (!safeTry("npm test -- --ci")) {
      console.error("tests failed");
      process.exit(4);
    }
  }

  safeTry("git config user.email box-bot@example.local");
  safeTry("git config user.name box-bot");
  safeTry("git add -A");
  safeTry(`git commit -m "box: task ${taskId} - ${taskTitle}"`);
  safeTry(`git push origin ${branch}`);

  if (boxAutoCreatePr) {
    const prResult = await createPullRequest({
      repoTarget: repo,
      tokenValue: token,
      branchName: branch,
      baseRef: baseBranch,
      title: taskTitle,
      taskKindValue: taskKind,
      taskIdValue: taskId
    });
    if (!prResult.ok) {
      console.error(`pr create skipped: ${prResult.reason}`);
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
